[versions]
kotlin = "2.2.21"
kotlinx-coroutines = "1.8.1"
kotlinx-io = "0.6.0"
kotest = "6.0.4"
ksp = "2.2.21-2.0.4" # <kotlin-verson>-<ksp-version>

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core-linux = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-linuxx64", version.ref = "kotlinx-coroutines" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-io-core-linux = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core-linuxx64", version.ref = "kotlinx-io" }
kotest-framework = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

[plugins]
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }